version: '3'
services:
  api:
    container_name: kisaco_app
    build: .
    ports:
      - "8080:8080"

  #######################################
  # MySQL server
  #######################################
  db:
    image: mysql:5.7.25
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: kisaco_db
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    networks:
      - default

  #######################################
  # PHP MY ADMIN
  #######################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8081:80
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass